CREATE DATABASE CLINICA
GO

USE CLINICA
GO

CREATE TABLE TIPO_USUARIO(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TIPO VARCHAR(20) UNIQUE NOT NULL
)

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TIPO_USUARIO INT NOT NULL FOREIGN KEY REFERENCES TIPO_USUARIO(ID),
	NOMBRE_USUARIO VARCHAR(50) NOT NULL UNIQUE,
	CONTRASEÑA VARCHAR(50) NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE PACIENTES(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRES VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	DNI INT NOT NULL UNIQUE,
	DOMICILIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE MEDICOS(
	ID INT PRIMARY KEY FOREIGN KEY REFERENCES TIPO_USUARIO(ID) NOT NULL,
	NOMBRES VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	DNI INT NOT NULL UNIQUE,
	MATRICULA INT NOT NULL UNIQUE,
	DOMICILIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE ESPECIALIDADES(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO BIT NOT NULL
)

CREATE TABLE ESPECIALIDAD_X_MEDICO(
	ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID) NOT NULL,
	ID_ESPECIALIDAD INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID) NOT NULL,
	PRIMARY KEY(ID_MEDICO, ID_ESPECIALIDAD)
)

CREATE TABLE HORARIOS_TRABAJO(
	ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS (ID),
	DIA VARCHAR(10) NOT NULL CHECK(DIA = 'LUNES' OR DIA = 'MARTES' OR DIA = 'MIERCOLES' OR DIA = 'MIÉRCOLES' OR DIA = 'JUEVES' OR DIA = 'VIERNES' OR DIA = 'SÁBADO' OR DIA = 'SABADO' OR DIA = 'DOMINGO'),
	H_ENTRADA TINYINT NOT NULL CHECK (H_ENTRADA > 0),
	H_SALIDA TINYINT NOT NULL CHECK (H_SALIDA > 0),
	LIBRE BIT NOT NULL,
	PRIMARY KEY (DIA, ID_MEDICO)
)

CREATE TABLE TURNOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID),
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID),
	ENTRADA TINYINT NOT NULL CHECK (ENTRADA > 0),
	FECHA DATE NOT NULL,
	OBSERVACIONES VARCHAR(200) NOT NULL,
	ESTADO BIT NOT NULL
)
GO

--ESPECIALIDADES--
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Cardiologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Cirugia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Gastroenterologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Oftalmologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Otorrinolaringologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Pediatria', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Ginecologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Obstetricia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Neumonologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Traumatologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Dermatologia', 1)
INSERT INTO ESPECIALIDADES (NOMBRE, ESTADO) VALUES ('Neurologia', 1)

--PACIENTES--
INSERT INTO PACIENTES (NOMBRES, APELLIDOS, DNI, DOMICILIO, EMAIL, FECHA_NACIMIENTO, ESTADO) VALUES ('Facundo', 'Marcati', 43182968, 'Bogota 542', 'facumarcati99@gmail.com', '04/01/2001', 1)
